version: '3.7'

services:

  user-cmd-api:
    container_name: user-cmd-api
    image: user-cmd-api:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  user-query-api:
    container_name: user-query-api
    image: user-query-api:latest
    deploy:
      replicas: 1
    restart: always
    ports:
     - target: 8082
       published: 8082
       protocol: tcp
       mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  bankAcc-cmd-api:
    container_name: bankacc-cmd-api
    image: bankacc-cmd-api:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 8091
        published: 8091
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"


  bankAcc-query-api:
    container_name: bankacc-query-api
    image: bankacc-query-api:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 9092
        published: 9092
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 2000
        published: 2000
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  user-oauth2:
    container_name: user-oauth2
    image: user-oauth2:latest
    deploy:
      replicas: 1
    restart: always
    ports:
      - target: 8083
        published: 8083
        protocol: tcp
        mode: host
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

networks:
  default:
    external:
      name: SpringBankNet