# spring
server.port: 8083

# mongodb
spring:
  data:
    mongodb:
      host: mongo-container
      port: 27017
      database: user

# security
security:
  oauth2:
    client:
      client-id: springbankClient
      client-secret: springbankSecret
      signing-key: springbankSigningKey
      token-validity-seconds: 3000
      refresh-token-validity-seconds: 1500


