# spring
server:
  port: 8082

# mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user

#security
security:
  oauth2:
    resource:
      jwt:
        key-value: springbankSigningKey

#logging:
#  file.name: user-query.log