# spring
server:
  port: 8082

axon:
  axonserver:
    servers: axon-server

# mongodb
spring:
  data:
    mongodb:
      host: mongo-container
      port: 27017
      database: user

#security
security:
  oauth2:
    resource:
      jwt:
        key-value: springbankSigningKey